version: 2
jobs:
  build:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - run:
          command: |
            sudo apt update
            sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
            sudo apt update
      - run: "composer install -n --prefer-dist --no-scripts --no-dev --optimize-autoloader"
    working_directory: ~/jinya
workflows:
  version: 2
  edge:
    jobs:
      - build