---
- name: Create jinya directory
  file:
    path: /var/www/jinya/
    state: directory
    mode: 0755
  become: yes
- name: Sync files to location
  synchronize:
    src: /vagrant/
    dest: /var/www/jinya/
    delete: yes
    recursive: yes
  become: true
- name: Copy htaccess
  copy:
    src: /vagrant/vagrant-files/roles/jinya/files/.htaccess
    dest: /var/www/jinya/public/.htaccess
    owner: apache
    group: apache
    mode: u=rwx,g=rwx,o=rwx
- name: Change permissions
  file:
    path: /var/www/jinya/
    mode: u=xrw,g=xrw,o=xrw
    recurse: yes
  become: yes